'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { fetchAllClinics, fetchAllPatients, fetchAllAppointments } from '@/lib/analytics';
import { calculate30DayRetention, calculateMAU, formatGrowthPercentage } from '@/lib/metrics';
import { format, subMonths, startOfMonth, endOfMonth } from 'date-fns';
import { FileText, Download, Calendar } from 'lucide-react';
import type { Clinic, Patient, Appointment } from '@/lib/analytics';

export default function ReportsPage() {
  const [loading, setLoading] = useState(false);
  const [clinics, setClinics] = useState<Clinic[]>([]);
  const [patients, setPatients] = useState<Patient[]>([]);
  const [appointments, setAppointments] = useState<Appointment[]>([]);

  useEffect(() => {
    const loadData = async () => {
      try {
        const [clinicsData, patientsData, appointmentsData] = await Promise.all([
          fetchAllClinics(),
          fetchAllPatients(),
          fetchAllAppointments(),
        ]);

        setClinics(clinicsData);
        setPatients(patientsData);
        setAppointments(appointmentsData);
      } catch (error) {
        console.error('Error loading reports data:', error);
      }
    };

    loadData();
  }, []);

  const generateMonthlyReport = () => {
    const now = new Date();
    const currentMonthStart = startOfMonth(now);
    const currentMonthEnd = endOfMonth(now);
    const prevMonthStart = startOfMonth(subMonths(now, 1));
    const prevMonthEnd = endOfMonth(subMonths(now, 1));

    const currentMonthAppointments = appointments.filter((apt) => {
      let aptDate: Date | null = null;
      if (apt.createdAt) {
        aptDate = apt.createdAt.toDate ? apt.createdAt.toDate() : new Date(apt.createdAt);
      }
      if (!aptDate && apt.date) {
        try {
          const parts = apt.date.toLowerCase().split(' ');
          const monthsMap: Record<string, number> = {
            'january': 0, 'february': 1, 'march': 2, 'april': 3,
            'may': 4, 'june': 5, 'july': 6, 'august': 7,
            'september': 8, 'october': 9, 'november': 10, 'december': 11
          };
          if (parts.length === 3) {
            const day = parseInt(parts[0]);
            const month = monthsMap[parts[1]];
            const year = parseInt(parts[2]);
            if (!isNaN(day) && month !== undefined && !isNaN(year)) {
              aptDate = new Date(year, month, day);
            }
          }
        } catch (e) {
          // Ignore
        }
      }
      if (!aptDate) return false;
      return aptDate >= currentMonthStart && aptDate <= currentMonthEnd;
    });

    const prevMonthAppointments = appointments.filter((apt) => {
      let aptDate: Date | null = null;
      if (apt.createdAt) {
        aptDate = apt.createdAt.toDate ? apt.createdAt.toDate() : new Date(apt.createdAt);
      }
      if (!aptDate) return false;
      return aptDate >= prevMonthStart && aptDate <= prevMonthEnd;
    });

    const retention = calculate30DayRetention(patients, appointments);
    const mau = calculateMAU(appointments, now);
    const appointmentGrowth = prevMonthAppointments.length > 0 
      ? formatGrowthPercentage(currentMonthAppointments.length, prevMonthAppointments.length)
      : '0%';

    const report = {
      reportType: 'Monthly Growth Report',
      period: format(now, 'MMMM yyyy'),
      generatedAt: format(now, 'PPpp'),
      metrics: {
        totalClinics: clinics.length,
        activeClinics: clinics.filter(c => c.onboardingStatus === 'Completed').length,
        totalPatients: patients.length,
        monthlyActiveUsers: mau,
        totalAppointments: appointments.length,
        monthlyAppointments: currentMonthAppointments.length,
        appointmentGrowth,
        retentionRate: `${retention.toFixed(1)}%`,
      },
    };

    return report;
  };

  const exportToText = (report: any) => {
    const content = `
KL intelligent Solutions - Monthly Growth Report
${report.period}
Generated: ${report.generatedAt}

KEY METRICS
-----------
Total Clinics: ${report.metrics.totalClinics}
Active Clinics: ${report.metrics.activeClinics}
Total Patients: ${report.metrics.totalPatients}
Monthly Active Users: ${report.metrics.monthlyActiveUsers}
Total Appointments: ${report.metrics.totalAppointments}
Monthly Appointments: ${report.metrics.monthlyAppointments}
Appointment Growth: ${report.metrics.appointmentGrowth}
30-Day Retention Rate: ${report.metrics.retentionRate}

---
Report generated by Kloqo SuperAdmin Dashboard
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kloqo-monthly-report-${format(new Date(), 'yyyy-MM')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportInvestorData = () => {
    const now = new Date();
    const monthlyStats = [];
    
    for (let i = 5; i >= 0; i--) {
      const monthDate = subMonths(now, i);
      const monthStart = startOfMonth(monthDate);
      const monthEnd = endOfMonth(monthDate);
      
      const monthAppointments = appointments.filter((apt) => {
        let aptDate: Date | null = null;
        if (apt.createdAt) {
          aptDate = apt.createdAt.toDate ? apt.createdAt.toDate() : new Date(apt.createdAt);
        }
        if (!aptDate) return false;
        return aptDate >= monthStart && aptDate <= monthEnd;
      });

      const monthPatients = patients.filter((patient) => {
        if (!patient.createdAt) return false;
        const createdDate = patient.createdAt.toDate ? patient.createdAt.toDate() : new Date(patient.createdAt);
        return createdDate >= monthStart && createdDate <= monthEnd;
      });

      monthlyStats.push({
        month: format(monthDate, 'MMM yyyy'),
        patients: monthPatients.length,
        appointments: monthAppointments.length,
        clinics: clinics.filter(c => {
          if (!c.registrationDate) return false;
          const regDate = c.registrationDate.toDate ? c.registrationDate.toDate() : new Date(c.registrationDate);
          return regDate >= monthStart && regDate <= monthEnd;
        }).length,
      });
    }

    const investorData = {
      company: 'Klo intelligent Solutions',
      product: 'Kloqo - Healthcare Appointment Platform',
      reportType: 'Investor Pitch Data',
      generatedAt: format(now, 'PPpp'),
      currentMetrics: {
        totalClinics: clinics.length,
        totalPatients: patients.length,
        totalAppointments: appointments.length,
        retentionRate: `${calculate30DayRetention(patients, appointments).toFixed(1)}%`,
        mau: calculateMAU(appointments, now),
      },
      monthlyTrends: monthlyStats,
      projections: {
        month3: { clinics: 20, mrr: 19980 },
        month6: { clinics: 50, mrr: 49950 },
        month12: { clinics: 100, mrr: 99900 },
      },
    };

    const content = JSON.stringify(investorData, null, 2);
    const blob = new Blob([content], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `kloqo-investor-data-${format(new Date(), 'yyyy-MM')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleGenerateMonthlyReport = () => {
    const report = generateMonthlyReport();
    exportToText(report);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Reports</h1>
        <p className="text-muted-foreground mt-1">Generate and export reports</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Calendar className="h-5 w-5" />
              <CardTitle>Monthly Growth Report</CardTitle>
            </div>
            <CardDescription>Comprehensive monthly metrics and growth summary</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">
              Generate a detailed report with key metrics including clinic count, patient growth, 
              appointment volume, and retention rates.
            </p>
            <Button onClick={handleGenerateMonthlyReport} className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Download Monthly Report
            </Button>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              <CardTitle>Investor Pitch Data</CardTitle>
            </div>
            <CardDescription>Data formatted for investor presentations</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground mb-4">
              Export key metrics, growth trends, and projections in JSON format 
              suitable for investor pitch decks and due diligence.
            </p>
            <Button onClick={exportInvestorData} variant="outline" className="w-full">
              <Download className="h-4 w-4 mr-2" />
              Export Investor Data
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* Report Preview */}
      <Card>
        <CardHeader>
          <CardTitle>Current Metrics Summary</CardTitle>
          <CardDescription>Quick overview of platform metrics</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Total Clinics</p>
              <p className="text-2xl font-bold">{clinics.length}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Total Patients</p>
              <p className="text-2xl font-bold">{patients.length}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Total Appointments</p>
              <p className="text-2xl font-bold">{appointments.length}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">30-Day Retention</p>
              <p className="text-2xl font-bold">
                {patients.length > 0 ? `${calculate30DayRetention(patients, appointments).toFixed(1)}%` : '0%'}
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card className="border-blue-200 bg-blue-50">
        <CardContent className="p-4">
          <p className="text-sm text-blue-800">
            <strong>Note:</strong> For PDF exports and more advanced report formatting, 
            consider integrating libraries like jsPDF or react-pdf. Current exports are in 
            text and JSON formats.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
